### ISSUE TITLE
add depeus dependency

### ISSUE THREAD

**Issue by k-okada** [ros/message_generation#2]
I'd like to add geneus dependency, currently it is within jsk_roseus repository but may be we have to create isolated repository that only includes genesu. This packages only depends on python.
https://github.com/jsk-ros-pkg/jsk_roseus/tree/master/geneus

I understand there are already genlisp exists, but our geneus is lisp message generator for our implementation of lisp. So they are different. Having multiple implementation is a kind of Lisp tradition.

c.f. http://answers.ros.org/question/193612/how-to-add-message-generator-in-ros-buildform/?comment=193628#comment-193628

**Comment by dirk-thomas** [comment]
What are the minimum dependencies of the `geneus` package? Currently it depends on `rospy` and `euslisp` which itself depends on a lot of other stuff (https://github.com/jsk-ros-pkg/jsk_roseus/blob/5db9067fa8d545f66945f926e83a771775be4303/euslisp/package.xml) which clearly is not feasible: `git`, `rosbuild`, `rostest`, `opengl`

Also do you expect it to build on ARM and all build dependencies being available on ARM platforms?

**Comment by k-okada** [comment]
it only depends on genmsg, (if genmsg provide python), please see https://github.com/k-okada/jsk_roseus/blob/new_geneus/geneus/package.xml

**Comment by dirk-thomas** [comment]
It still uses `rospack` internally: https://github.com/k-okada/jsk_roseus/blob/2ae97b9c9337b6b30fd0fc1756af14164192e57a/geneus/cmake/roseus.cmake#L211

It also tries to generate messages for all installed messages (just from reading the code, not running it): https://github.com/k-okada/jsk_roseus/blob/2ae97b9c9337b6b30fd0fc1756af14164192e57a/geneus/cmake/roseus.cmake#L206

It also installs to a weird location (just from reading the code, not running it): https://github.com/k-okada/jsk_roseus/blob/2ae97b9c9337b6b30fd0fc1756af14164192e57a/geneus/cmake/roseus.cmake#L4

The mixture of rosbuild support makes it very difficult to read the actual code. May be that part could be moved to `rosbuild`.

This needs more cleanup and then some documentation describing what exactly it does, e.g. where does it generate code, how is that code used afterwards etc.

**Comment by k-okada** [comment]
these file exists but not used, I created new repository just contains
geneus https://github.com/k-okada/geneus/tree/init_version for
re-writed/clean version. Sorry to confuse and take your time.

**Comment by dirk-thomas** [comment]
What is the purpose of the generated `manifest.l` file? It seems to contain the names of all ROS packages. Even the ones which the message package has no relation to.

The generated code seems to contain some duplicated code (e.g. in the `Imu.l`):

```
(in-package "ROS")
;;//! \htmlinclude Imu.msg.html
(if (not (find-package "STD_MSGS"))
  (ros::roseus-add-msgs "std_msgs"))
(if (not (find-package "GEOMETRY_MSGS"))
  (ros::roseus-add-msgs "geometry_msgs"))
(if (not (find-package "GEOMETRY_MSGS"))
  (ros::roseus-add-msgs "geometry_msgs"))
(if (not (find-package "GEOMETRY_MSGS"))
  (ros::roseus-add-msgs "geometry_msgs"))
```

May be your generator can deduplicate those before generating redundant code.

**Comment by k-okada** [comment]
What is the purpose of the generated manifest.l file? It seems to contain

> the names of all ROS packages. Even the ones which the message package has
> no relation to.

this is to support `(ros::load-ros-manifest "foo")` which load all related
.l files (and that we borrow idea from  roslib.load_manifest('foo') ), the
name list comes from  ${CATKIN_ORDERED_PACKAGES} in
https://github.com/k-okada/geneus/blob/init_version/cmake/geneus-extras.cmake.em#L57

The generated code seems to contain some duplicated code (e.g. in the Imu.l

> ):
> 
> (in-package "ROS")
> ;;//! \htmlinclude Imu.msg.html
> (if (not (find-package "STD_MSGS"))
>   (ros::roseus-add-msgs "std_msgs"))
> (if (not (find-package "GEOMETRY_MSGS"))
>   (ros::roseus-add-msgs "geometry_msgs"))
> (if (not (find-package "GEOMETRY_MSGS"))
>   (ros::roseus-add-msgs "geometry_msgs"))
> (if (not (find-package "GEOMETRY_MSGS"))
>   (ros::roseus-add-msgs "geometry_msgs"))
> 
> May be your generator can deduplicate those before generating redundant
> code.
> 
> thanks, fixed in
> https://github.com/k-okada/geneus/commit/d9b2540efe5878f344cd9acbe6876f8fba6e592e

**Comment by dirk-thomas** [comment]
A `manifest.l` file for a package like `std_msgs` should not contain references to unrelated packages like `turtlesim`, `test_roslaunch`, `rviz`. It should only ever list dependencies (direct or recursive).

**Comment by k-okada** [comment]
thanks, fixed in https://github.com/k-okada/geneus/commit/8f603aaa996527fc54c3b0147a52d3700a168934

**Comment by k-okada** [comment]
Hi

Any update? Is there anything that I have to fix, please let me know

**Comment by dirk-thomas** [comment]
Since adding a new message generator is not a very small change to ROS we think that you should write an email to ros-users@ to propose adding this message generator as a default and ask for feedback from the community.

It will be important to not introduce any dependencies which might lead to problems when building for different platforms like ARM.

Before actually adding it the following tasks need to happen:
- rename the "new" message generator package since it collides with an already release package `geneus`, we would propose `geneuslisp`
- release the new package `geneuslisp` - likely into _Indigo_ only - eventually even only into the upcoming _Jade_ depending on the discussion
- update the `message_generation` package to list the new generator as a dependency

It should also be checked before that all packages in the targeted ROS distro can be rebuild from source with the new generator in place to avoid running into issues when it is released to the buildfarm.

What are the dependencies of the client library using the newly generated code? Do you intent to also include that into `desktop` / `desktop_full`?

**Comment by k-okada** [comment]
ok, thanks. I'll do that.

> It should also be checked before that all packages in the targeted ROS distro can be rebuild from source with the new generator in place to avoid running into issues when it is released to the buildfarm.

How do I get list of the all packages? and is there way to run only message_generation process?

**Comment by dirk-thomas** [comment]
You should use the `rosinstall_generator` to fetch the sources of all released packages.

There is no way to only run the message generation.

**Comment by k-okada** [comment]
@dirk-thomas, I have sent e-mail to ros-users@ on new message generation a half month ago and it seems there are no objection. Can we move to next step? release new message generation and update message_generation package?

http://lists.ros.org/pipermail/ros-users/2014-October/069010.html

**Comment by tfoote** [comment]
@k-okada Thanks for circulating this to ros-users. There were no objections there. There are the technical checks in the comment above from @dirk-thomas which should be verified. 

And lastly if we're going to make this a default message generator, it's going to cost the whole community build time and bandwidth we should make sure it is accessible to the whole community. Right now from a quick search I can only find 2 tutorials in Japanese. We should have a full set of tutorials so that anyone can try out the new generators when we make them part of the default.

**Comment by k-okada** [comment]
ok  I have created several roseus tutorials on English, see http://wiki.ros.org/roseus/Tutorials, if you need more, let's me know.

I believe I already checked the comment from @dirk-thomas and create the package,  
https://github.com/jsk-ros-pkg/geneuslisp, https://github.com/jsk-ros-pkg/geneus
Either package name is ok for us (even it conflict with older version, we're ok to switch them)

**Comment by dirk-thomas** [comment]
I am sorry to follow up on this so late. I was very busy with other projects in the last months.

After extensive consideration, we came to the conclusion that we should not integrate it into _Indigo_. The rational is that _Indigo_ has already been released last summer and should be kept stable for our users. Instead we should integrate this new feature into the upcoming release _Jade_ as a default generator.

As this will be coming in as a low level dependency for the entire ROS ecosystem we'd like to get your confirmation on the following points that `geneus` is ready to be promoted.
- There have been multiple new releases of `geneus` recently (four versions in February: https://github.com/jsk-ros-pkg/geneus/blob/master/CHANGELOG.rst). Since every new release of a default message generator implies a complete rebuild of almost all ROS packages we want the default message generators to be very stable and only be released for important bug fixes (which should only be necessary a few times per year). Do you think `geneus` has reached that level of maturity by now?
- When `geneus` has been added as a default generator we require the maintainers to keep a close eye on the related Jenkins notification email. In case of problems we require immediate attention and timely fixes since otherwise all downstream packages are affected. I just want to make sure that you are aware of these responsibilities?
- Since `geneus` is a very low-level package it should strictly follow ROS (release) guidelines (e.g. package.xml in the source repo, no downloading of external data during the build). It currently does follow the standard ROS procedures - I just wanted to clarify it.
- Since the majority of the ROS packages (over 90%) compiles on ARM now it would be good if this would also be the case for geneus / euslisp. Do you think that it is viable for you to add support for ARM?
- Related it would be great to add unit tests to the package. E.g. `genpy` has a lot of tests to ensure its working as expected.

**Comment by dirk-thomas** [comment]
The beta of Jade will be in about one / two weeks. Please comment if you still consider to add it as a default language and also reply to the previous questions.

**Comment by k-okada** [comment]
sorry for late, I'll tackle this today.

## 

◉ Kei Okada

**Comment by k-okada** [comment]
Thanks for your decision. I'll answer your question inline.

> There have been multiple new releases of geneus recently (four versions in February: https://github.com/jsk-ros-pkg/geneus/blob/master/CHANGELOG.rst). Since every new release of a default message generator implies a complete rebuild of almost all ROS packages we want the default message generators to be very stable and only be released for important bug fixes (which should only be necessary a few times per year). Do you think geneus has reached that level of maturity by now?

I believe so, we have two serious bug recently (https://github.com/jsk-ros-pkg/geneus/pull/17, https://github.com/jsk-ros-pkg/geneus/pull/15), but besides that, I don't see any problem. I'll release final version within this week. 
We're using this for software basis on both APC and DRC competition, so the software is enough stable.

> When geneus has been added as a default generator we require the maintainers to keep a close eye on the related Jenkins notification email. In case of problems we require immediate attention and timely fixes since otherwise all downstream packages are affected. I just want to make sure that you are aware of these responsibilities?

Sure, @garaemon, @YoheiKakiuchi, @furushchev, @wkentaro and @k-okada can take care of this.

> Since geneus is a very low-level package it should strictly follow ROS (release) guidelines (e.g. package.xml in the source repo, no downloading of external data during the build). It currently does follow the standard ROS procedures - I just wanted to clarify it.

Yes of course.

> Since the majority of the ROS packages (over 90%) compiles on ARM now it would be good if this would also be the case for geneus / euslisp. Do you think that it is viable for you to add support for ARM?

Yes, currently I'm working on that -> https://github.com/tork-a/euslisp-release/issues/6

> Related it would be great to add unit tests to the package. E.g. genpy has a lot of tests to ensure its working as expected.

We're testing that on downstrem package https://github.com/jsk-ros-pkg/jsk_roseus/tree/master/roseus/test, to move this to geneus, geneus have to depend on euslisp/roseus  and that is too dangerous for now, I think.

**Comment by k-okada** [comment]
I've just released geneus for jade, which may be stable and we do not have plan to change the for a whilem

**Comment by dirk-thomas** [comment]
It still seems to not build on ARM yet: tork-a/euslisp-release#6

Regarding tests: you dont require the client library to have test coverage for the message generator package. Please take a look to the other message generators and what they cover in their tests.

**Comment by k-okada** [comment]
ARM should be fixed for newer version, as for tests. do you mean
https://github.com/ros/genpy/tree/indigo-devel/test ?
other generators does not have test code https://github.com/ros/genlisp
https://github.com/ros/gencpp, Or did I looking into wrong place?

## 

◉ Kei Okada

**Comment by dirk-thomas** [comment]
Yes, only `genpy` has unit tests. It would for sure be better if `gencpp` would have tests too. But for the interpreted code like Python it is even more important since the generator might even produce invalid syntax. Anyway adding tests was only a recommendation.

**Comment by dirk-thomas** [comment]
`geneus` has been added as a default generator to the `jade`-devel branch of message_generation.
